# Generated by Django 4.2.3 on 2023-11-30 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_app",
            "0005_alter_userdata_unique_together_userdata_stored_posts_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdata",
            options={"verbose_name_plural": "User Data"},
        ),
    ]
